# -*- coding: utf-8 -*-
"""python_final(new).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMdD_EMpMsAM1EpKige8OKi_YLfeako3
"""

!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

import datetime
import csv
import textwrap
import matplotlib.pyplot as plt
import matplotlib
import os

# 設定字型（支援中文）
matplotlib.font_manager.fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
matplotlib.rc('font', family='Taipei Sans TC Beta')

# 預設自動存檔的檔名
DEFAULT_CSV_FILE = "central_ledger.csv"


class Ledger:
    def __init__(self, initial_balance=0.0):
        self.initial_balance = float(initial_balance)
        self.transactions = []  # list of dicts

    def add_transaction(self, date_str, t_type, amount, category, note):
        # t_type: "收入" or "支出"
        try:
            amount = float(amount)
        except ValueError:
            raise ValueError("金額必須是數字")
        if amount < 0:
            raise ValueError("金額請填正數，收入或支出用類型區分")

        signed = amount if t_type == "收入" else -amount

        tx = {
            "date": date_str,
            "type": t_type,
            "amount": amount,
            "signed_amount": signed,
            "category": category,
            "note": note,
        }
        self.transactions.append(tx)

    def iter_transactions(self, only_today=False):
        if not only_today:
            for tx in self.transactions:
                yield tx
            return
        today_str = datetime.date.today().isoformat()
        for tx in self.transactions:
            if tx["date"] == today_str:
                yield tx

    def total_income_expense(self):
        income = 0.0
        expense = 0.0
        for tx in self.transactions:
            if tx["signed_amount"] >= 0:
                income += tx["signed_amount"]
            else:
                expense += -tx["signed_amount"]
        return income, expense

    def balance(self):
        income, expense = self.total_income_expense()
        return self.initial_balance + income - expense

    def summary_by_category(self):
        result = {}
        for tx in self.transactions:
            cat = tx["category"]
            signed = tx["signed_amount"]
            if cat not in result:
                result[cat] = {"income": 0.0, "expense": 0.0}
            if signed >= 0:
                result[cat]["income"] += signed
            else:
                result[cat]["expense"] += -signed
        return result

    def export_csv(self, filename=DEFAULT_CSV_FILE):
        """
        匯出為 CSV：
        第一列會寫一筆 type = '餘額' 的 meta row，用來記錄 initial_balance。
        後面每一列是一般交易。
        """
        fieldnames = ["date", "type", "category", "amount", "signed_amount", "note"]
        with open(filename, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            # 期初餘額的 meta row
            writer.writerow({
                "date": "INIT",
                "type": "期初餘額",
                "category": "",
                "amount": self.initial_balance,
                "signed_amount": self.initial_balance,
                "note": "",
            })
            # 寫入各筆交易
            for tx in self.transactions:
                writer.writerow({
                    "date": tx["date"],
                    "type": tx["type"],
                    "category": tx["category"],
                    "amount": tx["amount"],
                    "signed_amount": tx["signed_amount"],
                    "note": tx["note"],
                })
        return filename

    def load_csv(self, filename=DEFAULT_CSV_FILE):
        """
        從既有的 CSV 檔案載入交易紀錄與期初餘額。
        若檔案中有 type = '期初餘額' 的列，會用它的 amount 當作 initial_balance。
        其他列會被視為一般交易。
        """
        self.transactions = []
        self.initial_balance = 0.0

        with open(filename, "r", newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if not row:
                    continue
                row_type = row.get("type", "")
                # 期初餘額 meta row
                if row_type == "期初餘額":
                    try:
                        self.initial_balance = float(row.get("amount", 0) or 0)
                    except ValueError:
                        self.initial_balance = 0.0
                    continue

                date_str = row.get("date", "")
                if not date_str or date_str == "INIT":
                    continue

                # 一般交易
                self.add_transaction(
                    date_str,
                    row.get("type", "支出"),
                    row.get("amount", 0),
                    row.get("category", "其他"),
                    row.get("note", ""),
                )
                )
                # 輸入工具、類別設定、新增記帳流程
def safe_input(prompt=""):
    try:
        return input(prompt)
    except EOFError:
        return ""


def wrap_print(text, width=60):
    print("\n".join(textwrap.wrap(str(text), width)))


# 類別列表
DEFAULT_CATEGORIES = [
    "餐飲",
    "交通",
    "生活用品",
    "房租",
    "學習",
    "娛樂",
    "社交",
    "打工收入",
    "獎學金",
    "其他",
]

# 每個類別對應的提醒文字
CATEGORY_MESSAGES = {
    "餐飲": "很棒！有好好吃飯，身體才有力氣賺錢。",
    "交通": "路上小心安全，記得看紅綠燈。",
    "生活用品": "補給日常用品，生活會順很多。",
    "房租": "繳完房租，就有地方可以安心躺平。",
    "學習": "投資自己，是最划算的花費之一。",
    "娛樂": "適當放鬆一下也很重要，記得不要太超過就好。",
    "社交": "社交紀錄 +1，在世界上留下一點存在感。",
    "打工收入": "辛苦了！錢錢正在向你奔來。",
    "獎學金": "太強了，連錢都在稱讚你的努力。",
    "其他": "已記錄這筆收支，未來回頭看也不會一頭霧水。",
}


def daily_expense_for_date(ledger: Ledger, date_str: str) -> float:
    """計算某一天的總支出（金額加總，只有支出）"""
    total = 0.0
    for tx in ledger.transactions:
        if tx["date"] == date_str and tx["signed_amount"] < 0:
            total += -tx["signed_amount"]
    return total


def flow_add_transaction(ledger: Ledger):
    print("\n＝＝ 新增一筆記帳 ＝＝")

    def flow_add_transaction(ledger: Ledger):
    print("\n＝＝ 新增一筆記帳 ＝＝")

    # 一定要YYYY-MM-DD才能往下
    while True:
        today_str = datetime.date.today().isoformat()
        date_str = safe_input(
            f"日期（預設 {today_str}，直接 Enter 使用預設）："
        ).strip()
        if not date_str:
            date_str = today_str

        # 檢查日期格式
        try:
            datetime.date.fromisoformat(date_str)
            break
        except ValueError:
            wrap_print("日期格式不是 YYYY-MM-DD，請重新輸入。")

    # 一定要選支出 / 收入
    while True:
        print("\n這筆是收入還是支出？")
        print("1. 支出")
        print("2. 收入")
        t_choice = safe_input("輸入 1 或 2：").strip()

        if t_choice == "1":
            t_type = "支出"
            break
        elif t_choice == "2":
            t_type = "收入"
            break
        else:
            wrap_print("輸入錯誤，請輸入 1（支出）或 2（收入）。")

    # 金額驗證：一定要正數
    while True:
        amount_str = safe_input("金額（正數）：").strip()
        try:
            amount = float(amount_str)
            if amount <= 0:
                print("金額請輸入大於 0 的數字。")
                continue
            break
        except ValueError:
            print("金額格式怪怪的，再試一次（只能輸入數字）。")

    print("\n選擇一個類別：")
    for idx, cat in enumerate(DEFAULT_CATEGORIES, start=1):
        print(f"{idx}. {cat}")
    print(f"{len(DEFAULT_CATEGORIES)+1}. 自訂類別（自行輸入文字）")

    cat_choice = safe_input("輸入編號：").strip()
    category = ""
    if cat_choice.isdigit():
        c_idx = int(cat_choice)
        if 1 <= c_idx <= len(DEFAULT_CATEGORIES):
            category = DEFAULT_CATEGORIES[c_idx - 1]
        elif c_idx == len(DEFAULT_CATEGORIES) + 1:
            category = safe_input("輸入自訂類別名稱：").strip() or "其他"
        else:
            category = "其他"
    else:
        category = "其他"

    note = safe_input("備註（可以空白）：").strip()

    try:
        ledger.add_transaction(date_str, t_type, amount, category, note)
        wrap_print("已新增一筆記帳。")

        #  自動存檔：每新增一筆記帳就直接匯出到預設 CSV
        try:
            ledger.export_csv(DEFAULT_CSV_FILE)
        except Exception as e:
            wrap_print(f"自動存檔失敗（不影響本次記帳）：{e}")

        # 類別提醒
        msg = CATEGORY_MESSAGES.get(
            category, "已記錄這筆收支，持續記下去就會越來越有感。"
        )
        print(msg)

        # 日支出提醒（只看支出）
        daily_exp = daily_expense_for_date(ledger, date_str)
        if daily_exp < 500:
            wrap_print(
                f"今天（{date_str}）目前總支出 {daily_exp:.0f} 元，很棒！可以存錢了。"
            )
        elif daily_exp > 2000:
            wrap_print(
                f"今天（{date_str}）目前總支出 {daily_exp:.0f} 元，要注意消費囉！"
            )

        # 當前餘額提醒
        current_balance = ledger.balance()
        if current_balance < 1000:
            wrap_print(
                f"警告：目前剩餘金額只剩下 {current_balance:.0f} 元，再這樣可能會活不下去，記得收斂一下開支。"
            )

    except ValueError as e:
        wrap_print(f"新增失敗：{e}")


# 查看紀錄、統計總覽與圓餅圖
def flow_show_records(ledger: Ledger):
    if not ledger.transactions:
        wrap_print("目前還沒有任何記帳紀錄。先去加一筆看看。")
        return

    print("\n要看哪一種？")
    print("1. 只看今天")
    print("2. 看全部")
    choice = safe_input("輸入 1 或 2：").strip()
    only_today = (choice == "1")

    print("\n＝＝ 記帳紀錄 ＝＝")


    # 儲存用於繪圖的資料
    expense_by_category = {}

    # 取得交易紀錄
    for tx in ledger.iter_transactions(only_today=only_today):
        sign = "+" if tx["signed_amount"] >= 0 else "-"
        amt = abs(tx["signed_amount"])
        line = (
            f"{tx['date']}｜{tx['type']}｜{tx['category']}｜"
            f"{sign}{amt}｜備註：{tx['note']}"
        )
        print(line)

        # 只統計支出（負數）
        if tx["signed_amount"] < 0:
            cat = tx["category"]
            expense_by_category[cat] = expense_by_category.get(cat, 0.0) + amt

    print("\n＝＝ 已列出所有符合條件的紀錄 ＝＝\n")

    # 若沒有任何支出紀錄
    if not expense_by_category:
        wrap_print("在選定的範圍內沒有找到任何支出紀錄，無法產生統計圖表。")
        return

    # 準備繪圖資料
    categories = list(expense_by_category.keys())
    expenses = list(expense_by_category.values())

    # 中文字體
    plt.rcParams["font.sans-serif"] = ["Arial Unicode MS"]

    # 繪圖
    plt.figure(figsize=(8, 8))
    plt.pie(
        expenses,
        labels=categories,
        autopct="%1.1f%%",
        startangle=90,
        wedgeprops={"edgecolor": "black"},
    )
    plt.title(f"{'今天' if only_today else '所有'}支出類別分佈圓餅圖")
    plt.axis("equal")

    # 🚀 非阻塞顯示，不會卡住主選單
    plt.show(block=False)

    # 儲存用於繪圖的資料
    expense_by_category = {}

    for tx in ledger.iter_transactions(only_today=only_today):
        sign = "+" if tx["signed_amount"] >= 0 else "-"
        amt = abs(tx["signed_amount"])
        line = (
            f"{tx['date']}｜{tx['type']}｜{tx['category']}｜"
            f"{sign}{amt}｜備註：{tx['note']}"
        )
        print(line)
        # 收集用於圓餅圖的支出數據
        if tx["signed_amount"] < 0:  # 僅統計支出
            cat = tx["category"]
            expense = amt  # 取正數
            expense_by_category[cat] = expense_by_category.get(cat, 0.0) + expense
    print("＝＝ 已列出所有符合條件的紀錄 ＝＝\n")

    # 檢查是否有支出數據
    if not expense_by_category:
        wrap_print("在選定的範圍內（今天/全部），沒有找到任何支出紀錄可供統計。")
        return

    # 準備繪圖數據
    categories = list(expense_by_category.keys())
    expenses = list(expense_by_category.values())

    # Colab 環境中需要中文支援
    plt.rcParams["font.sans-serif"] = ["Arial Unicode MS"]
    # plt.rcParams['axes.unicode_minus'] = False

    # 開始繪圖
    plt.figure(figsize=(8, 8))
    plt.pie(
        expenses,
        labels=categories,
        autopct="%1.1f%%",
        startangle=90,
        wedgeprops={"edgecolor": "black"},
    )
    plt.title(f"{'今天' if only_today else '所有'}支出類別分佈圓餅圖")
    plt.axis("equal")  # 確保圓餅圖是圓的
    plt.show()  # 在 Colab 中顯示圖表
    safe_input("\n圖表顯示完畢，按 Enter 返回主選單...")



def flow_show_summary(ledger: Ledger):
    if not ledger.transactions:
        wrap_print("目前還沒有任何記帳紀錄，沒有東西可以統計。")
        return

    income, expense = ledger.total_income_expense()
    balance = ledger.balance()

    print("\n＝＝ 統計總覽 ＝＝")
    print(f"總收入：{income}")
    print(f"總支出：{expense}")
    print(f"期初餘額：{ledger.initial_balance}")
    print(f"目前餘額：{balance}")

    print("\n按類別統計：")
    summary = ledger.summary_by_category()
    for cat, val in summary.items():
        print(f"- {cat}｜收入：{val['income']}｜支出：{val['expense']}")
    print("＝＝ 統計結束 ＝＝\n")

    # 餘額太低的提醒
    if balance < 1000:
       wrap_print("提醒：目前餘額已低於 1000 元，之後花錢要更小心一點。")

# 匯出 CSV、主程式
def flow_export_csv(ledger: Ledger):
    if not ledger.transactions:
        wrap_print("沒有資料，不需要匯出。")
        return
    filename = safe_input(
        f"輸入要匯出的檔名（預設 {DEFAULT_CSV_FILE}）："
    ).strip()
    if not filename:
        filename = DEFAULT_CSV_FILE
    if not filename.endswith(".csv"):
        filename += ".csv"
    fname = ledger.export_csv(filename)
    wrap_print(
        f"已匯出到檔案：{fname}\n在 Colab 左邊檔案列表可以找到，然後下載。"
    )


def main():
    wrap_print(
        "歡迎使用《記帳系統》：\n"
        "專心把每一筆收支記下來，順便幫你看今天花多少、還能不能活。"
    )

    # 是否載入之前的紀錄？
    use_old = False
    while True:
        ans = safe_input("是否要從之前存好的 CSV 檔案載入紀錄？(y/n)：").strip().lower()
        if ans in ("y", "n", ""):
            use_old = ans == "y"
            break
        wrap_print("輸入錯誤，請輸入 y 或 n。")

    ledger = None

    if use_old:
        filename = safe_input(
            f"請輸入要載入的檔名（直接 Enter 代表 {DEFAULT_CSV_FILE}）："
        ).strip()
        if not filename:
            filename = DEFAULT_CSV_FILE

        if os.path.exists(filename):
            ledger = Ledger(initial_balance=0.0)
            try:
                ledger.load_csv(filename)
                last_balance = ledger.balance()
                wrap_print(
                    f"已從 {filename} 載入之前的記帳紀錄。"
                    f"\n上次結束時的餘額約為 {last_balance:.0f} 元，這次會從這個金額繼續記。"
                )
            except Exception as e:
                wrap_print(
                    f"載入舊資料失敗：{e}\n這次會改用空白帳本重新開始。"
                )
                ledger = None
        else:
            wrap_print(
                f"找不到檔案：{filename}\n請確認檔案在同一個資料夾或 Colab 左側已上傳。"
                "\n這次會改用空白帳本重新開始。"
            )
            ledger = None

    # 如果沒有載入舊紀錄就問這次的期初餘額
    if ledger is None:
        init = safe_input("請輸入這次的期初餘額（可以直接 Enter 代表 0）：").strip()
        if not init:
            init = 0
        try:
            initial_balance = float(init)
        except ValueError:
            wrap_print("期初餘額輸入怪怪的，當作 0。")
            initial_balance = 0.0

        ledger = Ledger(initial_balance=initial_balance)

    # 主選單
    while True:
        print("\n＝＝ 主選單 ＝＝")
        print("1. 記一筆帳")
        print("2. 查看紀錄")
        print("3. 查看統計")
        print("4. 匯出 CSV")
        print("5. 離開")
        choice = safe_input("請輸入選項編號：").strip()

        if choice == "1":
            flow_add_transaction(ledger)
        elif choice == "2":
            flow_show_records(ledger)
        elif choice == "3":
            flow_show_summary(ledger)
        elif choice == "4":
            flow_export_csv(ledger)
        elif choice == "5":
            # 提醒下載 CSV 備份
            if ledger.transactions:
                wrap_print(
                    f"提醒：這次的記帳紀錄已自動存成 {DEFAULT_CSV_FILE}。"
                    "\n如果你是在 Colab，記得到左邊檔案列表把這個檔案下載到自己電腦備份。"
                )
            wrap_print("感謝使用，穩定記帳就是慢慢打造安全感。")
            break
        else:
            wrap_print("按錯了，請重新選一次。")


if __name__ == "__main__":
    main()
