# -*- coding: utf-8 -*-
"""python_final(new).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15etoxwe3sgOfIeRCcsE8iNvgbJ7TndkQ
"""

!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

import datetime
import csv
import textwrap
import matplotlib.pyplot as plt
import matplotlib
import os

# 設定字型（支援中文）
matplotlib.font_manager.fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
matplotlib.rc('font', family='Taipei Sans TC Beta')

# 預設自動存檔的檔名
DEFAULT_CSV_FILE = "central_ledger.csv"


class Ledger:
    def __init__(self, initial_balance=0.0):
        self.initial_balance = float(initial_balance)
        self.transactions = []  # list of dicts

    def add_transaction(self, date_str, t_type, amount, category, note):
        # t_type: "收入" or "支出"
        try:
            amount = float(amount)
        except ValueError:
            raise ValueError("金額必須是數字")
        if amount < 0:
            raise ValueError("金額請填正數，收入或支出用類型區分")

        signed = amount if t_type == "收入" else -amount

        tx = {
            "date": date_str,
            "type": t_type,
            "amount": amount,
            "signed_amount": signed,
            "category": category,
            "note": note,
        }
        self.transactions.append(tx)

    def iter_transactions(self, only_today=False):
        if not only_today:
            for tx in self.transactions:
                yield tx
            return
        today_str = datetime.date.today().isoformat()
        for tx in self.transactions:
            if tx["date"] == today_str:
                yield tx

    def total_income_expense(self):
        income = 0.0
        expense = 0.0
        for tx in self.transactions:
            if tx["signed_amount"] >= 0:
                income += tx["signed_amount"]
            else:
                expense += -tx["signed_amount"]
        return income, expense

    def balance(self):
        income, expense = self.total_income_expense()
        return self.initial_balance + income - expense

    def summary_by_category(self):
        result = {}
        for tx in self.transactions:
            cat = tx["category"]
            signed = tx["signed_amount"]
            if cat not in result:
                result[cat] = {"income": 0.0, "expense": 0.0}
            if signed >= 0:
                result[cat]["income"] += signed
            else:
                result[cat]["expense"] += -signed
        return result

    def export_csv(self, filename=DEFAULT_CSV_FILE):
        """
        匯出為 CSV：
        第一列會寫一筆 type = '餘額' 的 meta row，用來記錄 initial_balance。
        後面每一列是一般交易。
        """
        fieldnames = ["date", "type", "category", "amount", "signed_amount", "note"]
        with open(filename, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            # 期初餘額的 meta row
            writer.writerow({
                "date": "INIT",
                "type": "期初餘額",
                "category": "",
                "amount": self.initial_balance,
                "signed_amount": self.initial_balance,
                "note": "",
            })
            # 寫入各筆交易
            for tx in self.transactions:
                writer.writerow({
                    "date": tx["date"],
                    "type": tx["type"],
                    "category": tx["category"],
                    "amount": tx["amount"],
                    "signed_amount": tx["signed_amount"],
                    "note": tx["note"],
                })
        return filename

    def load_csv(self, filename=DEFAULT_CSV_FILE):
        """
        從既有的 CSV 檔案載入交易紀錄與期初餘額。
        若檔案中有 type = '期初餘額' 的列，會用它的 amount 當作 initial_balance。
        其他列會被視為一般交易。
        """
        self.transactions = []
        self.initial_balance = 0.0

        with open(filename, "r", newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if not row:
                    continue
                row_type = row.get("type", "")
                # 期初餘額 meta row
                if row_type == "期初餘額":
                    try:
                        self.initial_balance = float(row.get("amount", 0) or 0)
                    except ValueError:
                        self.initial_balance = 0.0
                    continue

                date_str = row.get("date", "")
                if not date_str or date_str == "INIT":
                    continue

                # 一般交易
                self.add_transaction(
                    date_str,
                    row.get("type", "支出"),
                    row.get("amount", 0),
                    row.get("category", "其他"),
                    row.get("note", ""),
                )